### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by andychase**
Hey, your link was broken! You could also change your server so it serves `index.aspx` pages.

Cool to see you're active on Github!

### CODE REVIEW

**Comment by DaoWen** [comment]
Ah crap—I forgot that ouuuuch was running on mono. I should probably fix that. But the fix will be to switch it all to php or something instead, so changing the link to aspx will be counterproductive. Thanks for the notification. Who knows how many years it would have stayed broken otherwise...

**Comment by DaoWen** [comment]
Oh, I didn't know you could close your own issues. Interesting.

I was planning to leave this open until I actually moved the site over to php (and thus fixed the link). I was thinking about reopening, but since you deleted your fork it doesn't let me reopen anymore... I wonder why they do that. The patch still exists, so you'd think it would be fine... :confused:

**Comment by andychase** [comment]
Yeah I just don't like having a bunch of forks in my repository lists haha, you can't reopen because github can't actually pull from somewhere that doesn't exist, but you can always reference issues to keep the convo going!

**Comment by DaoWen** [comment]
I agree, no point in keeping forks around if you're not using them.

I'm pretty sure that <a href="http://programmers.stackexchange.com/a/256977/142980">you can delete a fork as soon as you've submitted a pull request</a> without affecting the pull request (since it's just a patch, and the patch is stored in the upstream repo). You can still add ".patch" on the end of this PR's URL to see the patch you submitted (i.e., I could still `curl ${URL}.patch | git am` if I wanted to). So I don't see why deleting your fork would make it so I can't reopen this. I guess it was just an arbitrary choice by some GitHub developer. :unamused:

**Pull request closed without merging**
